// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	aggregate "github.com/xlsmart-api/sf-payment/model/aggregate"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the RepositoryInterface type
type MockRepository struct {
	mock.Mock
}

// CheckIdempotency provides a mock function with given fields: ctx, key
func (_m *MockRepository) CheckIdempotency(ctx context.Context, key string) (bool, string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CheckIdempotency")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CreatePaymentTransaction provides a mock function with given fields: ctx, payment
func (_m *MockRepository) CreatePaymentTransaction(ctx context.Context, payment *aggregate.PaymentTransaction) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *aggregate.PaymentTransaction) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePaymentWebhook provides a mock function with given fields: ctx, webhook
func (_m *MockRepository) CreatePaymentWebhook(ctx context.Context, webhook *aggregate.PaymentWebhook) error {
	ret := _m.Called(ctx, webhook)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *aggregate.PaymentWebhook) error); ok {
		r0 = rf(ctx, webhook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentByReferenceID provides a mock function with given fields: ctx, referenceID
func (_m *MockRepository) GetPaymentByReferenceID(ctx context.Context, referenceID string) (*aggregate.PaymentTransaction, error) {
	ret := _m.Called(ctx, referenceID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByReferenceID")
	}

	var r0 *aggregate.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*aggregate.PaymentTransaction, error)); ok {
		return rf(ctx, referenceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *aggregate.PaymentTransaction); ok {
		r0 = rf(ctx, referenceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggregate.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, referenceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveIdempotency provides a mock function with given fields: ctx, key, endpoint, statusCode, responseBody
func (_m *MockRepository) SaveIdempotency(ctx context.Context, key string, endpoint string, statusCode int, responseBody string) error {
	ret := _m.Called(ctx, key, endpoint, statusCode, responseBody)

	if len(ret) == 0 {
		panic("no return value specified for SaveIdempotency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string) error); ok {
		r0 = rf(ctx, key, endpoint, statusCode, responseBody)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaymentTransaction provides a mock function with given fields: ctx, payment
func (_m *MockRepository) UpdatePaymentTransaction(ctx context.Context, payment *aggregate.PaymentTransaction) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *aggregate.PaymentTransaction) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
